# Generated by Django 5.2 on 2025-10-30 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogpost", "0004_alter_blogpost_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="slug",
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
